version: '2'

services:
  macarena:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    container_name: macarena
    command: nodemon --config .nodemon.json ./bin/server
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.macarena.env

  db:
    image: postgres:9.6.3-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/tmp/postgres/:/var/lib/postgresql/data
    env_file:
      - ./.postgres.env
